name: SecurePass
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^6.1.0
  lottie: ^3.1.0
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Define assets to be included in the project
  assets:
    - lib/assets/pg.json
